add solution for dz5-calendar
js-tasks-ru/htmlcss-20240216_dosug4 pull request #11
Opened 2024-03-10 19:45 UTC by Chunkes

2024-03-10 19:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 11:02 UTC, GSemikozov requested changes

2024-03-12 11:02 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 36px;
`28 26 32`

2024-03-12 21:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 21:29 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-03-12 21:53 UTC, GSemikozov approved these changes

2024-03-12 21:53 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-03-12 21:54 UTC, GSemikozov approved these changes

2024-03-12 21:54 UTC, merged