add solution for 3 module 1 task
js-tasks-ru/htmlcss-20240216_dosug4 pull request #3
Opened 2024-02-29 19:23 UTC by Chunkes

2024-02-29 19:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-03 13:18 UTC, GSemikozov requested changes

2024-03-03 13:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    width: 189px;
ширину не фиксируем

2024-03-03 13:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    left: 643px;
свойства которые касаются внешней геометрии / позиционирования ни в коем случае не задаем на уровне блока

2024-03-03 13:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    left: 643px;
top + left удаляем

2024-03-03 13:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    border-radius: 15px;
не по макету (по макету - 8)

2024-03-03 13:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: pointer;
а вот чего здесь не хватает - так это паддингов и свойств для описания текста

2024-03-03 13:18 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
pointer-events: none

2024-03-04 21:59 UTC, GSemikozov requested changes

2024-03-04 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    padding: 10px 20px;
`15px 15px 14px`

2024-03-04 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    font-size: 16px;
а еще `line-height: 19px; font-family: Roboto, sans-serif; font-weight: 500`

2024-03-04 21:59 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: default;
а это лишнее

2024-03-05 22:15 UTC, GSemikozov approved these changes

2024-03-05 22:16 UTC, merged