add solution for skeleton
js-tasks-ru/htmlcss-20240216_dosug4 pull request #8
Opened 2024-03-06 20:24 UTC by Chunkes

2024-03-06 20:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-12 21:52 UTC, GSemikozov requested changes

2024-03-12 21:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle_1 {
.skeleton__rectangle_small?

2024-03-12 21:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 172px;
в процентах

2024-03-12 21:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__rectangle_2 {
.skeleton__rectangle_large?

2024-03-12 21:52 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    max-width: 257px;
в процентах

2024-03-13 15:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-03-15 15:07 UTC, GSemikozov approved these changes

2024-03-15 15:07 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2024-03-15 15:08 UTC, GSemikozov approved these changes

2024-03-15 15:08 UTC, merged